In [ ]:
a = [1, 2, 3]
b = [1, 2, 3]

print(a == b)   # True
print(a is b)   # False

True
False


In [ ]:
# Mutable
a = [1, 2, 3]
a[0] = 100
print(a)   # [100, 2, 3]

# Immutable
b = (1, 2, 3)
# b[0] = 100   # TypeError

print(b)   # (1, 2, 3)

[100, 2, 3]
(1, 2, 3)


In [ ]:
print(0.1 + 0.2 == 0.3)

False


In [ ]:
point = (10, 20)

print(point)

def get_student():
    return ("Manya", 20, "Python")

student = get_student()

print(student)

locations = {
    (10, 20): "Bangalore",
    (30, 40): "Mysore"
}

print(locations[(10, 20)])

(10, 20)
('Manya', 20, 'Python')
Bangalore


In [ ]:
# List vs Dictionary lookup

numbers = [10, 20, 30, 40, 50]

student = {
    "name": "Manya",
    "age": 20,
    "course": "Python"
}

# List lookup - O(n)
print(30 in numbers)

# Dictionary lookup - O(1) average
print(student["course"])

True
Python


In [ ]:
import numpy as np

# 1. range()
a = range(0, 5)
print(a)
print(list(a))

# 2. numpy.arange()
b = np.arange(0, 5)
print(b)

# 3. Float example
c = np.arange(0, 1, 0.2)
print(c)

# range() with float would cause an error:
# range(0, 1, 0.2)  # TypeError

range(0, 5)
[0, 1, 2, 3, 4]
[0 1 2 3 4]
[0.  0.2 0.4 0.6 0.8]


In [ ]:
# Original list
a = [1, 2, 3]

# 1. append()
b = a.copy()
b.append([4, 5])
print("append :", b)

# 2. extend()
c = a.copy()
c.extend([4, 5])
print("extend :", c)

# 3. insert()
d = a.copy()
d.insert(1, [4, 5])
print("insert :", d)

append : [1, 2, 3, [4, 5]]
extend : [1, 2, 3, 4, 5]
insert : [1, [4, 5], 2, 3]


In [ ]:
a, *b, c = [10, 20, 30, 40, 50]

print("a =", a)
print("b =", b)
print("c =", c)

a = 10
b = [20, 30, 40]
c = 50


In [ ]:
print(-7 / 2)    # Division → -3.5
print(-7 // 2)   # Floor division → -4
print(-7 % 2)    # Modulus → 1
print(-7 ** 2)   # Exponentiation → -49

-3.5
-4
1
-49


In [ ]:
import numpy as np

# Python list
a = [1, 2, 3, 4, 5]
print([x * 2 for x in a])

# NumPy array
b = np.array([1, 2, 3, 4, 5])
print(b * 2)

[2, 4, 6, 8, 10]
[ 2  4  6  8 10]


In [ ]:
matrix1 = [[0] * 3 for _ in range(3)]
matrix2 = [[0] * 3] * 3

matrix1[0][0] = 99
matrix2[0][0] = 99

print(matrix1)
print(matrix2)

[[99, 0, 0], [0, 0, 0], [0, 0, 0]]
[[99, 0, 0], [99, 0, 0], [99, 0, 0]]


In [ ]:
x = [1, 2, 3]
y = x
x = x + [4]

print("x =", x)
print("y =", y)

a = [1, 2, 3]
b = a
a += [4]

print("a =", a)
print("b =", b)

x = [1, 2, 3, 4]
y = [1, 2, 3]
a = [1, 2, 3, 4]
b = [1, 2, 3, 4]


In [ ]:
for i in range(5):
    pass

print(i)   # Output: 4

4


In [ ]:
print("10" + "20")      # 1020
print(10 + 20)          # 30
print("10" * 3)         # 101010
print(10 * "3")         # 3333333333

# This causes an error:
# print("10" + 20)

print(int("10") + 20)   # 30

1020
30
101010
3333333333
30


In [ ]:
print(0 or 5)
print(5 or 0)
print(None or "hello")

print(0 and 5)
print(5 and 10)

print([] or "default")
print([0] or "default")

5
5
hello
0
10
default
[0]


In [1]:
a = 10
b = 20

# Swap using tuple unpacking
a, b = b, a

print("a =", a)
print("b =", b)

a = 20
b = 10


In [2]:
# Swiggy Order Calculator

price = float(input("Enter item price: ₹"))
quantity = int(input("Enter quantity: "))

# Subtotal
subtotal = price * quantity

# GST (18%)
gst = subtotal * 0.18

# Amount before delivery
amount_before_delivery = subtotal + gst

# Delivery charge
if amount_before_delivery < 500:
    delivery = 40
else:
    delivery = 0

# Final total
total = amount_before_delivery + delivery

# Bill
print("\nSubtotal:      ₹{:.2f}".format(subtotal))
print("GST (18%):     ₹{:.2f}".format(gst))
print("Delivery:      ₹{:.2f}".format(delivery))
print("------------------------")
print("Total:         ₹{:.2f}".format(total))

Enter item price: ₹150
Enter quantity: 3

Subtotal:      ₹450.00
GST (18%):     ₹81.00
Delivery:      ₹0.00
------------------------
Total:         ₹531.00


In [3]:
temp = float(input("Enter temperature: "))
unit = input("Enter unit (C/F): ").upper()

if unit == "C":
    result = (temp * 9/5) + 32
    print(f"{temp:.2f}°C = {result:.2f}°F")
elif unit == "F":
    result = (temp - 32) * 5/9
    print(f"{temp:.2f}°F = {result:.2f}°C")
else:
    print("Error: Invalid unit. Please enter C or F.")

Enter temperature: 98.6
Enter unit (C/F): c
98.60°C = 209.48°F


In [4]:
num = int(input("Enter a 4-digit number: "))

d1 = num // 1000
d2 = (num // 100) % 10
d3 = (num // 10) % 10
d4 = num % 10

sum_digits = d1 + d2 + d3 + d4

print("Sum of digits:", sum_digits)

Enter a 4-digit number: 1234
Sum of digits: 10


In [5]:
value = input("Enter a value: ")

try:
    value = int(value)
    print("Value:", value)
    print("Type: int")

except ValueError:
    try:
        value = float(value)
        print("Value:", value)
        print("Type: float")

    except ValueError:
        print("Value:", value)
        print("Type: str")

Enter a value: 42
Value: 42
Type: int


In [6]:
income = float(input("Enter annual income: ₹"))

tax = 0

print("\nTax Breakdown:")

if income <= 300000:
    print("Up to ₹3,00,000: ₹0.00")

else:
    print("Up to ₹3,00,000: ₹0.00")

    if income > 300000:
        amount = min(income, 700000) - 300000
        slab_tax = amount * 0.05
        tax += slab_tax
        print(f"₹3,00,001 - ₹7,00,000: ₹{slab_tax:.2f}")

    if income > 700000:
        amount = min(income, 1000000) - 700000
        slab_tax = amount * 0.10
        tax += slab_tax
        print(f"₹7,00,001 - ₹10,00,000: ₹{slab_tax:.2f}")

    if income > 1000000:
        amount = min(income, 1200000) - 1000000
        slab_tax = amount * 0.15
        tax += slab_tax
        print(f"₹10,00,001 - ₹12,00,000: ₹{slab_tax:.2f}")

    if income > 1200000:
        amount = min(income, 1500000) - 1200000
        slab_tax = amount * 0.20
        tax += slab_tax
        print(f"₹12,00,001 - ₹15,00,000: ₹{slab_tax:.2f}")

    if income > 1500000:
        amount = income - 1500000
        slab_tax = amount * 0.30
        tax += slab_tax
        print(f"Above ₹15,00,000: ₹{slab_tax:.2f}")

print("-----------------------------")
print(f"Total Tax: ₹{tax:.2f}")

Enter annual income: ₹800000

Tax Breakdown:
Up to ₹3,00,000: ₹0.00
₹3,00,001 - ₹7,00,000: ₹20000.00
₹7,00,001 - ₹10,00,000: ₹10000.00
-----------------------------
Total Tax: ₹30000.00


In [7]:
pan = input("Enter PAN: ")

if len(pan) != 10:
    print("Invalid PAN - length must be exactly 10")
elif not pan[:5].isalpha():
    print("Invalid PAN - first 5 characters must be letters")
elif not pan[:5].isupper():
    print("Invalid PAN - first 5 letters must be uppercase")
elif not pan[5:9].isdigit():
    print("Invalid PAN - characters 6 to 9 must be digits")
elif not pan[9].isalpha():
    print("Invalid PAN - last character must be a letter")
elif not pan[9].isupper():
    print("Invalid PAN - last letter must be uppercase")
else:
    print("Valid PAN")

Enter PAN: ABCDE1234F
Valid PAN


In [8]:
runs = int(input("Enter runs scored: "))
balls = int(input("Enter balls faced: "))

if balls == 0:
    print("Cannot calculate strike rate: balls faced cannot be 0.")
else:
    strike_rate = (runs / balls) * 100

    print(f"Strike Rate: {strike_rate:.2f}")

    if strike_rate > 150:
        print("Classification: Explosive (T20 finisher)")
    elif strike_rate > 100:
        print("Classification: Aggressive (Top order T20)")
    elif strike_rate >= 75:
        print("Classification: Steady (ODI anchor)")
    else:
        print("Classification: Defensive (Test match)")

Enter runs scored: 60
Enter balls faced: 40
Strike Rate: 150.00
Classification: Aggressive (Top order T20)


In [9]:
weight = float(input("Enter weight (kg): "))
height_cm = float(input("Enter height (cm): "))

height_m = height_cm / 100
bmi = weight / (height_m ** 2)

print(f"BMI: {bmi:.2f}")

if bmi < 18.5:
    print("Category: Underweight")
elif bmi <= 22.9:
    print("Category: Normal")
elif bmi <= 24.9:
    print("Category: Overweight")
elif bmi <= 29.9:
    print("Category: Obese Class I")
else:
    print("Category: Obese Class II")

Enter weight (kg): 60
Enter height (cm): 165
BMI: 22.04
Category: Normal


In [10]:
n = 5

for i in range(1, n + 1):
    for j in range(1, i + 1):
        print(j, end=" ")
    print()

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [11]:
n = 5

# Upper half
for i in range(1, n + 1):
    print(" " * (n - i), end="")

    for j in range(1, i + 1):
        print(j, end=" ")

    for j in range(i - 1, 0, -1):
        print(j, end=" ")

    print()

# Lower half
for i in range(n - 1, 0, -1):
    print(" " * (n - i), end="")

    for j in range(1, i + 1):
        print(j, end=" ")

    for j in range(i - 1, 0, -1):
        print(j, end=" ")

    print()

    1 
   1 2 1 
  1 2 3 2 1 
 1 2 3 4 3 2 1 
1 2 3 4 5 4 3 2 1 
 1 2 3 4 3 2 1 
  1 2 3 2 1 
   1 2 1 
    1 


In [12]:
n = 5

for i in range(n):
    for j in range(n):
        if i == 0 or i == n - 1 or j == 0 or j == n - 1:
            print("*", end=" ")
        else:
            print(" ", end=" ")
    print()

* * * * * 
*       * 
*       * 
*       * 
* * * * * 


In [13]:
n = 5

for i in range(n):
    print(" " * (n - i), end="")

    value = 1

    for j in range(i + 1):
        print(value, end=" ")

        value = value * (i - j) // (j + 1)

    print()

     1 
    1 1 
   1 2 1 
  1 3 3 1 
 1 4 6 4 1 


In [14]:
n = 5

for i in range(n):
    for j in range(i + 1):
        print(chr(65 + j), end=" ")
    print()

A 
A B 
A B C 
A B C D 
A B C D E 


In [15]:
armstrong = []

for num in range(1, 10000):
    temp = num
    digits = 0

    # Count number of digits
    while temp > 0:
        digits += 1
        temp //= 10

    # Calculate sum of digits raised to the power of digits
    temp = num
    total = 0

    while temp > 0:
        digit = temp % 10
        total += digit ** digits
        temp //= 10

    if total == num:
        armstrong.append(num)

print("Armstrong numbers:")
print(", ".join(map(str, armstrong)))
print("Count:", len(armstrong))

Armstrong numbers:
1, 2, 3, 4, 5, 6, 7, 8, 9, 153, 370, 371, 407, 1634, 8208, 9474
Count: 16


In [16]:
n = int(input("Enter N: "))

a = 0
b = 1
total = 0

print("Fibonacci series:", end=" ")

for i in range(n):
    print(a, end=" ")
    total += a

    a, b = b, a + b

print()
print("Sum:", total)

Enter N: 5
Fibonacci series: 0 1 1 2 3 
Sum: 7


In [17]:
n = int(input("Enter N: "))

def is_prime(num):
    if num < 2:
        return False

    i = 2
    while i * i <= num:   # checks only up to √num
        if num % i == 0:
            return False
        i += 1

    return True


if is_prime(n):
    print(n, "is Prime")
else:
    print(n, "is Not Prime")

prime_sum = 0

for num in range(2, n + 1):
    if is_prime(num):
        prime_sum += num

print("Sum of primes from 2 to", n, "=", prime_sum)

Enter N: 10
10 is Not Prime
Sum of primes from 2 to 10 = 17


In [18]:
num = int(input("Enter a number: "))

original = num

if num < 0:
    print("Reversed:", -num)
    print("Not Palindrome")
else:
    reverse = 0
    temp = num

    while temp > 0:
        digit = temp % 10
        reverse = reverse * 10 + digit
        temp //= 10

    print("Reversed:", reverse)

    if original == reverse:
        print("Palindrome")
    else:
        print("Not Palindrome")

Enter a number: 121
Reversed: 121
Palindrome


In [20]:
a = int(input("Enter first positive integer: "))
b = int(input("Enter second positive integer: "))

x = a
y = b

# Euclidean algorithm for HCF
while y != 0:
    x, y = y, x % y

hcf = x

# HCF × LCM = a × b
lcm = (a * b) // hcf

print("HCF:", hcf)
print("LCM:", lcm)

Enter first positive integer: 12
Enter second positive integer: 18
HCF: 6
LCM: 36


In [21]:
sentence = input("Enter a sentence: ")

total_characters = len(sentence)
words = 0
vowels = 0
consonants = 0
digits = 0
spaces = 0
special_characters = 0

in_word = False

for ch in sentence:   # Single pass
    if ch.isalpha():
        if ch.lower() in "aeiou":
            vowels += 1
        else:
            consonants += 1

        if not in_word:
            words += 1
            in_word = True

    elif ch.isdigit():
        digits += 1
        if not in_word:
            words += 1
            in_word = True

    elif ch.isspace():
        spaces += 1
        in_word = False

    else:
        special_characters += 1

print("\n----- String Scanner -----")
print("Total characters:", total_characters)
print("Total words:", words)
print("Vowels:", vowels)
print("Consonants:", consonants)
print("Digits:", digits)
print("Spaces:", spaces)
print("Special characters:", special_characters)

Enter a sentence: order came on time

----- String Scanner -----
Total characters: 18
Total words: 4
Vowels: 7
Consonants: 8
Digits: 0
Spaces: 3
Special characters: 0


In [22]:
marks = list(map(int, input("Enter 10 marks: ").split()))

maximum = marks[0]
minimum = marks[0]
total = 0

for mark in marks:
    if mark > maximum:
        maximum = mark

    if mark < minimum:
        minimum = mark

    total += mark

average = total / len(marks)

above_average = 0
second_highest = None

for mark in marks:
    if mark > average:
        above_average += 1

    if mark != maximum:
        if second_highest is None or mark > second_highest:
            second_highest = mark

print("Maximum:", maximum)
print("Minimum:", minimum)
print("Average:", average)
print("Students above average:", above_average)
print("Second highest:", second_highest)

Enter 10 marks: 85 72 90 65 88 95 76 80 92 70
Maximum: 95
Minimum: 65
Average: 81.3
Students above average: 5
Second highest: 92


In [23]:
review = input("Enter Swiggy review: ")

words = review.lower().split()

frequency = {}

for word in words:
    word = word.strip(".,!?;:")

    if word in frequency:
        frequency[word] += 1
    else:
        frequency[word] = 1

# Sort words by frequency in descending order
sorted_words = sorted(frequency.items(), key=lambda x: x[1], reverse=True)

print("\nWord Frequency:")
for word, count in sorted_words:
    print(word, ":", count)

# Most frequent word
most_frequent_word, highest_count = sorted_words[0]

print("\nMost frequent word:", most_frequent_word)
print("Count:", highest_count)

Enter Swiggy review: food was hot and food is very tasty

Word Frequency:
food : 2
was : 1
hot : 1
and : 1
is : 1
very : 1
tasty : 1

Most frequent word: food
Count: 2


In [24]:
states = {
    "Karnataka": "Bengaluru",
    "Maharashtra": "Mumbai",
    "Tamil Nadu": "Chennai",
    "Kerala": "Thiruvananthapuram",
    "Rajasthan": "Jaipur"
}

while True:
    print("\n----- Indian States CRUD -----")
    print("1. Add State")
    print("2. Update Capital")
    print("3. Delete State")
    print("4. Search State")
    print("5. Display All States")
    print("6. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        state = input("Enter state: ")
        capital = input("Enter capital: ")

        if state in states:
            print("State already exists.")
        else:
            states[state] = capital
            print("State added successfully.")

    elif choice == "2":
        state = input("Enter state to update: ")

        if state in states:
            capital = input("Enter new capital: ")
            states[state] = capital
            print("Capital updated successfully.")
        else:
            print("State not found.")

    elif choice == "3":
        state = input("Enter state to delete: ")

        if state in states:
            del states[state]
            print("State deleted successfully.")
        else:
            print("State not found.")

    elif choice == "4":
        state = input("Enter state to search: ")

        if state in states:
            print("Capital:", states[state])
        else:
            print("Not found")

    elif choice == "5":
        print("\nStates and Capitals:")
        for state in sorted(states):
            print(state, "->", states[state])

    elif choice == "6":
        print("Program exited.")
        break

    else:
        print("Invalid choice. Please try again.")


----- Indian States CRUD -----
1. Add State
2. Update Capital
3. Delete State
4. Search State
5. Display All States
6. Exit
Enter your choice: 1
Enter state: karnataka
Enter capital: bengalaru
State added successfully.

----- Indian States CRUD -----
1. Add State
2. Update Capital
3. Delete State
4. Search State
5. Display All States
6. Exit
Enter your choice: 6
Program exited.


In [25]:
section_a = {"Python", "Java", "C++", "SQL"}
section_b = {"Java", "JavaScript", "Python", "Go", "SQL"}

# (a) Languages known by BOTH
both = section_a & section_b

# (b) Languages ONLY by Section A
only_a = section_a - section_b

# (c) Languages ONLY by Section B
only_b = section_b - section_a

# (d) Total unique languages
total_unique = section_a | section_b

# (e) Languages exclusive to one section
exclusive = section_a ^ section_b

print("Both sections:", both)
print("Only Section A:", only_a)
print("Only Section B:", only_b)
print("Total unique languages:", len(total_unique))
print("Exclusive languages:", exclusive)

Both sections: {'Python', 'Java', 'SQL'}
Only Section A: {'C++'}
Only Section B: {'Go', 'JavaScript'}
Total unique languages: 6
Exclusive languages: {'Go', 'C++', 'JavaScript'}


In [26]:
prices = (3845, 3902, 3878, 3955, 4012, 3998, 4055)

days = ("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")

# (a) Maximum price and day
max_price = max(prices)
max_day = days[prices.index(max_price)]

# (b) Minimum price and day
min_price = min(prices)
min_day = days[prices.index(min_price)]

# (c) Average price
average = sum(prices) / len(prices)

# (d) Biggest single-day gain
biggest_gain = prices[1] - prices[0]
gain_from = days[0]
gain_to = days[1]

for i in range(1, len(prices)):
    gain = prices[i] - prices[i - 1]

    if gain > biggest_gain:
        biggest_gain = gain
        gain_from = days[i - 1]
        gain_to = days[i]

# (e) Total volatility
volatility = 0

for i in range(1, len(prices)):
    volatility += abs(prices[i] - prices[i - 1])

print("Maximum price:", max_price, "on", max_day)
print("Minimum price:", min_price, "on", min_day)
print("Average price: ₹{:.2f}".format(average))
print("Biggest single-day gain: ₹{} ({} to {})".format(
    biggest_gain, gain_from, gain_to
))
print("Total volatility: ₹", volatility)

Maximum price: 4055 on Sun
Minimum price: 3845 on Mon
Average price: ₹3949.29
Biggest single-day gain: ₹77 (Wed to Thu)
Total volatility: ₹ 286


In [27]:
numbers = [10, 20, 30, 20, 40, 50, 10, 60, 70, 30,
           80, 90, 50, 100, 110, 80, 120, 130, 140, 150]

unique_numbers = set(numbers)

duplicates = []
exactly_once = []

for num in unique_numbers:
    count = numbers.count(num)

    if count > 1:
        duplicates.append(num)
    elif count == 1:
        exactly_once.append(num)

print("Unique numbers:", unique_numbers)
print("Numbers appearing more than once:", duplicates)
print("Numbers appearing exactly once:", exactly_once)

Unique numbers: {130, 100, 70, 40, 10, 140, 110, 80, 50, 20, 150, 120, 90, 60, 30}
Numbers appearing more than once: [10, 80, 50, 20, 30]
Numbers appearing exactly once: [130, 100, 70, 40, 140, 110, 150, 120, 90, 60]


In [29]:
sentence = input("Enter a sentence: ")

cleaned = ""

for ch in sentence:
    if ch.isalnum():
        cleaned += ch.lower()

if cleaned == cleaned[::-1]:
    print("Palindrome")
else:
    print("Not Palindrome")

Enter a sentence: A man,a plan,a canal:Panama=palindrome
Not Palindrome


In [30]:
sentence = input("Enter a sentence: ")

words = sentence.split()
result = []

for word in words:
    new_word = word[0].upper() + word[1:].lower()
    result.append(new_word)

print("Title Case:", " ".join(result))

Enter a sentence: hello  world from bengalaru
Title Case: Hello World From Bengalaru


In [31]:
message = input("Enter message: ")
shift = int(input("Enter shift value: "))

encrypted = ""

for ch in message:
    if ch.isupper():
        encrypted += chr((ord(ch) - ord('A') + shift) % 26 + ord('A'))
    elif ch.islower():
        encrypted += chr((ord(ch) - ord('a') + shift) % 26 + ord('a'))
    else:
        encrypted += ch

print("Encrypted message:", encrypted)

Enter message: hello india
Enter shift value: 3
Encrypted message: khoor lqgld


In [32]:
def calculate_gst(amount, gst_rate=18, gst_inclusive=False):
    if gst_inclusive:
        total_amount = amount
        base_amount = amount / (1 + gst_rate / 100)
        gst_amount = total_amount - base_amount
    else:
        base_amount = amount
        gst_amount = amount * gst_rate / 100
        total_amount = base_amount + gst_amount

    return (
        round(base_amount, 2),
        round(gst_amount, 2),
        round(total_amount, 2)
    )


print(calculate_gst(1000))
print(calculate_gst(1180, gst_inclusive=True))
print(calculate_gst(500, gst_rate=5))

(1000, 180.0, 1180.0)
(1000.0, 180.0, 1180)
(500, 25.0, 525.0)


In [33]:
def power(base, exp):
    if exp == 0:
        return 1

    if exp < 0:
        return 1 / power(base, -exp)

    return base * power(base, exp - 1)


print(power(2, 10))
print(power(5, 0))
print(power(3, -2))

1024
1
0.1111111111111111


In [34]:
import numpy as np

# (a) Create 5x5 identity matrix
matrix = np.eye(5)

print("Identity Matrix:")
print(matrix)

# (b) Multiply every element by 10
matrix = matrix * 10

print("\nAfter multiplying by 10:")
print(matrix)

# (c) Transpose the matrix
# An identity matrix is symmetric, so its transpose is itself.
transpose = matrix.T

print("\nTranspose:")
print(transpose)

# (d) Sum of diagonal elements
diagonal_sum = np.trace(matrix)

print("\nSum of diagonal elements:", diagonal_sum)

# (e) Sum of all elements
total_sum = np.sum(matrix)

print("Sum of all elements:", total_sum)

Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

After multiplying by 10:
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]

Transpose:
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]

Sum of diagonal elements: 50.0
Sum of all elements: 50.0


In [35]:
import numpy as np

sales = np.array([12000, 18500, 14200, 22100, 19800, 35200, 28400])
days = np.array(["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"])

# (a) Total weekly sales
total_sales = np.sum(sales)

# (b) Daily average
average_sales = np.mean(sales)

# (c) Day with maximum sales
max_day = days[np.argmax(sales)]

# (d) Number of days above weekly average
above_average = np.sum(sales > average_sales)

# (e) Percentage growth from Monday to Sunday
growth = ((sales[-1] - sales[0]) / sales[0]) * 100

# (f) Day-on-day percentage changes
day_on_day = ((sales[1:] - sales[:-1]) / sales[:-1]) * 100

print("Total weekly sales: ₹", total_sales)
print("Daily average: ₹{:.2f}".format(average_sales))
print("Maximum sales day:", max_day)
print("Days above average:", above_average)
print("Monday to Sunday growth: {:.2f}%".format(growth))
print("Day-on-day % changes:", np.round(day_on_day, 2))

Total weekly sales: ₹ 150200
Daily average: ₹21457.14
Maximum sales day: Sat
Days above average: 3
Monday to Sunday growth: 136.67%
Day-on-day % changes: [ 54.17 -23.24  55.63 -10.41  77.78 -19.32]


In [36]:
import numpy as np

# Create a 5x5 array filled with 1
matrix = np.ones((5, 5), dtype=int)

# Make the interior 0 using slicing
matrix[1:-1, 1:-1] = 0

print(matrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
